version: "3"

services:
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_USER: $DOLI_DB_USER
      MARIADB_PASSWORD: $DOLI_DB_PASSWORD
      MARIADB_ROOT_PASSWORD: $DOLI_DB_ROOT_PASSWORD
      MARIADB_DATABASE: $DOLI_DB_NAME
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/db:/var/lib/mysql
    labels:
      - "traefik.enable=false"

  web:
    image: tuxgasy/dolibarr
    environment:
      DOLI_DB_HOST: $COMPOSE_PROJECT_NAME-mariadb-1
      DOLI_DB_USER: $DOLI_DB_USER
      DOLI_DB_PASSWORD: $DOLI_DB_PASSWORD
      DOLI_DB_NAME: $DOLI_DB_NAME
      DOLI_URL_ROOT: 'https://$HOST'
      PHP_INI_DATE_TIMEZONE: '$TZ'
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "homepage.group=Productivité"
      - "homepage.name=Dolibarr"
      - "homepage.icon=https://user-images.githubusercontent.com/24292300/64095022-ef2f0700-cd5d-11e9-8855-d6be38b31bdd.png"
      - "homepage.href=https://$HOST"
      - "homepage.description=Open Source ERP & CRM pour l'entreprise"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
    