services:
  server:
    image: mitmproxy/mitmproxy:10.4.2
    restart: unless-stopped
    # docker run --rm -it -p 8080:8080 -p 127.0.0.1:8081:8081 mitmproxy/mitmproxy mitmweb --web-host 0.0.0.0
    # command: ["mitmweb", "--web-host", "0.0.0.0"]
    ports:
    - 3128:8080
    labels:
      - "traefik.enable=true"

      ### Web UI (HTTP/HTTPS)
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME-ui.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME-ui.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME-ui.tls.certresolver=letsencrypt"
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-ui.service=$COMPOSE_PROJECT_NAME-ui"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME-ui.loadbalancer.server.port=8081"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://${HOST}/"
      - "homepage.description=$HOME_DESCRIPTION"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
