services:
  anythingllm:
    image: mintplexlabs/anythingllm:latest
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    # user: 1000:1000
    environment:
      - PORT=3001
      - NODE_ENV=production
      - VECTOR_DB=lancedb
      - STORAGE_DIR=/app/server/storage
      - TARGET_OCR_LANG=eng,fra
      - SIG_KEY=$SIG_KEY
      - SIG_SALT=$SIG_SALT
      - LLM_PROVIDER=$LLM_PROVIDER
      - OPEN_MODEL_PREF=$OPEN_MODEL_PREF
      - EMBEDDING_ENGINE=$EMBEDDING_ENGINE
      - OPEN_AI_KEY=$OPEN_AI_KEY
      - EMBEDDING_MODEL_PREF=$EMBEDDING_MODEL_PREF
    volumes:
      - "$JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/server/storage:/app/server/storage"
      - "$JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/collector/hotdir/:/app/collector/hotdir"
      - "$JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/collector/outputs/:/app/collector/outputs"
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=3001"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.middlewares=forward-auth-verify"

      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://${HOST}"
      - "homepage.description=$HOME_DESCRIPTION"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
    