services:
  anythingllm:
    image: mintplexlabs/anythingllm:latest
    restart: unless-stopped
    depends_on:
      - weaviate
    cap_add:
      - SYS_ADMIN
    user: 1000:1000
    environment:
      - PORT=3001
      - NODE_ENV=production
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - VECTOR_DB=weaviate # or chromadb, qdrant, etc.
      - WEAVIATE_URL=http://$COMPOSE_PROJECT_NAME-weaviate-1:8080
      - STORAGE_DIR=/app/server/storage/data
    volumes:
      # - $DOCUMENTS_ROOT:/app/server/storage/data
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME:/app/server/storage
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=3001"

      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://${HOST}/web/index.html"
      - "homepage.description=$HOME_DESCRIPTION"

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.4
    restart: unless-stopped
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-openai
      - ENABLE_MODULES=text2vec-openai
      - OPENAI_APIKEY=$OPENAI_API_KEY
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/weaviate-data:/var/lib/weaviate

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
    