# docker run -d -p 8081:8081 -v /path/to/downloads:/downloads ghcr.io/alexta69/metube

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/appdata:/config
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/downloads:/downloads
    ports:
      - 6881:6881
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=8080"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.middlewares=forward-auth-verify"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://$HOST"
      - "homepage.description=$HOME_DESCRIPTION"
      # - "homepage.widget.type=qbittorrent"
      # - "homepage.widget.url=https://$HOST"
      # - "homepage.widget.username=admin"
      # - "homepage.widget.password=$ADMIN_PASSWORD"
      # - "homepage.widget.enableLeechProgress=true"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
    
