services:
  agent:
    image: grafana/pdc-agent:latest
    restart: unless-stopped
    command:
      - token glc_eyJvIjoiMTE2Njg1MiIsIm4iOiJwZGMtam9obmxvZy1kZWZhdWx0LXBkYy1mNGU3Y2IiLCJrIjoicWdzZDY5aTQ0M1Q0M1E2QVQ4SDNVanpFIiwibSI6eyJyIjoicHJvZC1ldS13ZXN0LTIifX0=
      - cluster prod-eu-west-2
      - gcloud-hosted-grafana-id 976886
    labels:
      - "traefik.enable=false"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
