services:
  app:
    # https://bitwarden.com/help/install-and-deploy-unified-beta/#using-docker-compose
    image: bitwarden/self-host:beta
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - globalSettings__mail__replyToEmail=$globalSettings__mail__replyToEmail
      - globalSettings__mail__smtp__host=$globalSettings__mail__smtp__host
      - globalSettings__mail__smtp__port=$globalSettings__mail__smtp__port
      - globalSettings__mail__smtp__ssl=$globalSettings__mail__smtp__ssl
      - globalSettings__mail__smtp__username=$globalSettings__mail__smtp__username
      - globalSettings__mail__smtp__password=$globalSettings__mail__smtp__password
      - BW_ENABLE_SSL=false
      - BW_DB_PROVIDER=postgresql
      - BW_DB_SERVER=$COMPOSE_PROJECT_NAME-db-1
      - BW_DB_DATABASE=$DB_DATABASE
      - BW_DB_USERNAME=$DB_USERNAME
      - BW_DB_PASSWORD=$DB_PASSWORD
      - globalSettings__hibpApiKey=$globalSettings__hibpApiKey
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/etc:/etc/bitwarden
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/logs:/var/log/bitwarden
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=8080"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://${HOST}/"
      - "homepage.description=$HOME_DESCRIPTION"

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $DB_USERNAME']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
      PGDATA: /var/lib/postgresql/data/pgdata
    labels:
      - "traefik.enable=false"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
