services:
  puppet:
    image: ghcr.io/voxpupuli/puppetserver:latest
    environment:
      PUPPETSERVER_HOSTNAME: puppet
      PUPPETSERVER_PORT: 8140
      PUPPETDB_HOSTNAME: puppetdb
      PUPPETDB_SERVER_URLS: http://puppetdb:8081
      PUPPETDB_SSL_PORT: 8081
      USE_PUPPETDB: true
      AUTOSIGN: false
      CSR_ATTRIBUTES: '{"custom_attributes": { "challengePassword": "foobar" }, "extension_requests": { "pp_project": "foo" } }'
      # For private repos, use git@github.com:user/repo.git and provide SSH keys
      # R10K_REMOTE: https://github.com/betadots/demo-control-repo.git
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/puppet-code:/etc/puppetlabs/code
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=8140"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://$HOST"
      - "homepage.description=$HOME_DESCRIPTION"

  puppetdb:
    image: ghcr.io/voxpupuli/puppetdb:latest
    environment:
      - USE_PUPPETSERVER=false
      - PUPPETSERVER_HOSTNAME=puppet
      - PUPPETSERVER_PORT=8140
      - PUPPETDB_SSL_PORT=8081
      - PUPPETDB_POSTGRES_HOSTNAME=postgres
      - PUPPETDB_POSTGRES_PORT=5432
      - PUPPETDB_PASSWORD=$POSTGRES_PASSWORD
      - PUPPETDB_USER=$POSTGRES_USER
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/puppetdb:/opt/puppetlabs/server/data/puppetdb
    restart: unless-stopped
    # ports:
    #   - 8081:8081

  postgres:
    image: docker.io/postgres:16-alpine
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/postgres:/var/lib/postgresql/data
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/postgresql_init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  puppetboard:
    image: ghcr.io/voxpupuli/puppetboard:latest
    environment:
      - PUPPETDB_HOST=puppetdb
      - PUPPETDB_PORT=8081 # use this for TLS
      # - PUPPETDB_PORT=8080  # Use this for non-TLS
      - PUPPETBOARD_PORT=8088
      - SECRET_KEY=$BOARD_SECRET_KEY  # Long random String : python3 -c 'import secrets; print(secrets.token_hex())'
      # if you wanna use SSL, you need to provide the following variables
      # see the README.md for more information, look for "Generate additional certificates"
    #   - PUPPETDB_SSL_VERIFY=/etc/puppetlabs/puppet/ssl/certs/ca.pem
    #   - PUPPETDB_KEY=/etc/puppetlabs/puppet/ssl/private_keys/puppetboard.pem
    #   - PUPPETDB_CERT=/etc/puppetlabs/puppet/ssl/certs/puppetboard.pem
    # volumes:
    #   - puppetserver-ssl:/etc/puppetlabs/puppet/ssl
    restart: unless-stopped
    depends_on:
      - puppet
    # ports:
    #   - 8088:8088

  # hdm:
  #   image: ghcr.io/betadots/hdm:latest
  #   restart: unless-stopped
  #   environment:
  #     - SECRET_KEY_BASE=9dea7603c008dec285e4b231602a00b2
  #   volumes:
  #     - ./hdm_config/hdm.yml:/hdm/config/hdm.yml:ro
  #     - ./puppet-code:/etc/puppetlabs/code
    # ports:
    #   - 3000:3000

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
