services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=listmonk
      - POSTGRES_DB=listmonk
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk"]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"

  app:
    restart: unless-stopped
    image: listmonk/listmonk:latest
    environment:
      - TZ=$TZ
      - LISTMONK_app__address=0.0.0.0:9000
      - LISTMONK_app__admin_username=admin
      - LISTMONK_app__admin_password=$ADMIN_PASSWORD
      - LISTMONK_db__host=$COMPOSE_PROJECT_NAME-db-1
      - LISTMONK_db__port=5432
      - LISTMONK_db__user=listmonk
      - LISTMONK_db__password=$POSTGRES_PASSWORD
      - LISTMONK_db__database=listmonk
      - LISTMONK_db__ssl_mode=disable
    # hostname: $HOST # Recommend using FQDN for hostname
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=9000"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://$HOST"
      - "homepage.description=$HOME_DESCRIPTION"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
