services:
  cloudquery:
    image: ghcr.io/cloudquery/cloudquery:latest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
    - CLOUDQUERY_API_KEY=$CLOUDQUERY_API_KEY
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/config.yml:/config.yml
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/cache:/cache/.cq 
    command: ["sync", "/config.yml", "--cq-dir", "/cache/.cq"]
    labels:
      - "traefik.enable=false"
      # - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      # - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      # - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      # - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=17745"
      # - "homepage.group=$HOME_GROUP"
      # - "homepage.name=$HOME_NAME"
      # - "homepage.icon=$HOME_ICON"
      # - "homepage.href=https://$HOST"
      # - "homepage.description=$HOME_DESCRIPTION"

  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $DB_USER']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      PGDATA: /var/lib/postgresql/data/pgdata
    labels:
      - "traefik.enable=false"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
