services:
  db:
    image: postgres:16
    shm_size: 1g
    restart: unless-stopped
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: windmill
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  windmill_server:
    image: ghcr.io/windmill-labs/windmill:main
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@$COMPOSE_PROJECT_NAME-db-1/windmill?sslmode=disable
      - MODE=server
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/worker_logs:/tmp/windmill/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=8000"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://$HOST"
      - "homepage.description=$HOME_DESCRIPTION"

  windmill_worker:
    image: ghcr.io/windmill-labs/windmill:main
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@$COMPOSE_PROJECT_NAME-db-1/windmill?sslmode=disable
      - MODE=worker
      - WORKER_GROUP=default
    depends_on:
      db:
        condition: service_healthy
    # to mount the worker folder to debug, KEEP_JOB_DIR=true and mount /tmp/windmill
    volumes:
      # mount the docker socket to allow to run docker containers from within the workers
      - /var/run/docker.sock:/var/run/docker.sock
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/worker_dependency_cache:/tmp/windmill/cache
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/worker_logs:/tmp/windmill/logs

  ## This worker is specialized for "native" jobs. Native jobs run in-process and thus are much more lightweight than other jobs
  windmill_worker_native:
    # Use ghcr.io/windmill-labs/windmill-ee:main for the ee
    image: ghcr.io/windmill-labs/windmill:main
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@$COMPOSE_PROJECT_NAME-db-1/windmill?sslmode=disable
      - MODE=worker
      - WORKER_GROUP=native
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/worker_logs:/tmp/windmill/logs

  lsp:
    image: ghcr.io/windmill-labs/windmill-lsp:latest
    restart: unless-stopped
    expose:
      - 3001
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/lsp_cache:/root/.cache

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK

