# This is the recommended way of running Baserow using docker-compose for most users.
# See https://baserow.io/docs/installation%2Finstall-with-docker for more details.
version: "3.4"

services:
  app:
    image: baserow/baserow:1.13.2
    restart: unless-stopped
    environment:
      TZ: $TZ
      BASEROW_PUBLIC_URL: https://$HOST
    ports:
      - "8059:80"
      # - "443:443"
    volumes:
      - $JOHNCLOUD_ROOT/baserow/data:/baserow/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.baserow.rule=Host(`$HOST`)"
      - "traefik.http.routers.baserow.entrypoints=websecure"
      - "traefik.http.routers.baserow.tls.certresolver=letsencrypt"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK

