services:
  sumologic-collector:
    image: sumologic/collector:latest
    restart: unless-stopped
    environment:
      - SUMO_ACCESS_ID=$SUMO_ACCESS_ID
      - SUMO_ACCESS_KEY=$SUMO_ACCESS_KEY
      - SUMO_COLLECTOR_NAME=$SUMO_COLLECTOR_NAME
      - SUMO_CLOBBER=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=false"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
    
