version: "3.8"

services:
  app:
    image: kopia/kopia:latest
    container_name: backup_app
    hostname: backup_app
    restart: unless-stopped
    # ports:
    #     - 51515:51515
    # Setup the server that provides the web gui
    command:
        - server
        - start
        - --disable-csrf-token-checks
        - --insecure
        - --address=0.0.0.0:51515
        - --without-password
    environment:
        # Set repository password
        KOPIA_PASSWORD: $KOPIA_PASSWORD
        USER: $KOPIA_USER
    volumes:
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
        # Mount local folders needed by kopia
        - $BACKUP_ROOT/backup/config:/app/config
        - $BACKUP_ROOT/backup/cache:/app/cache
        - $BACKUP_ROOT/backup/logs:/app/logs
        - $JOHNCLOUD_ROOT:/source
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backup.rule=Host(`backup.$HOST`)"
      - "traefik.http.routers.backup.entrypoints=websecure"
      - "traefik.http.routers.backup.tls.certresolver=letsencrypt"
      - "traefik.http.services.backup.loadbalancer.server.port=51515"
      - "traefik.http.routers.backup.middlewares=forward-auth-verify"
      - "homepage.group=Platform"
      - "homepage.name=Kopia"
      - "homepage.icon=kopia.svg"
      - "homepage.href=https://backup.$HOST"
      - "homepage.description=Backup system"

networks:
  default:
    external: true
    name: traefik-proxy
    
