services:
  ldap:
    image: osixia/openldap
    ports:
      - 389:389
      - 636:636
    restart: unless-stopped
    environment:
      - LDAP_ORGANISATION=johncloud
      - LDAP_DOMAIN=johncloud.fr
      - LDAP_ADMIN_PASSWORD=$BIND_PASSWORD
      - LDAP_RFC2307BIS_SCHEMA=true
      - "LDAP_BASE_DN=dc=johncloud,dc=fr"
    volumes:  ## will need to configure this if you want persistent storage for ldap
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/data:/var/lib/ldap
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/config:/etc/ldap/slapd.d
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.tcp.routers.ldap-srv.entrypoints=ldaps"
    #   - "traefik.tcp.routers.ldap-srv.tls=true"
    #   - "traefik.tcp.routers.ldap-srv.tls.certresolver=letsencrypt"
    #   - "traefik.tcp.routers.ldap-srv.rule=HostSNI(`${HOST}`)"
    #   - "traefik.tcp.services.ldap-srv.loadbalancer.server.port=1636"
      # - "traefik.docker.network=proxy"
  
  openldap-ui:
    image: wheelybird/ldap-user-manager:v1.5
    environment:
      - LDAP_URI=ldap://$COMPOSE_PROJECT_NAME-ldap-1
      - LDAP_BASE_DN=dc=johncloud,dc=fr
      - LDAP_REQUIRE_STARTTLS=FALSE
      - LDAP_ADMINS_GROUP=admins
      - LDAP_ADMIN_BIND_DN=cn=admin,dc=johncloud,dc=fr
      - LDAP_ADMIN_BIND_PWD=admin
      - LDAP_IGNORE_CERT_ERRORS=true
      - PASSWORD_HASH=SSHA
      - SERVER_HOSTNAME=${HOST}
    depends_on:
      - ldap
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ldap-web-https.entrypoints=websecure"
      - "traefik.http.routers.ldap-web-https.tls=true"
      - "traefik.http.routers.ldap-web-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.ldap-web-https.rule=Host(`${HOST}`)"
      # - "traefik.http.services.ldap-web-https.loadbalancer.server.port=5000"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://$HOST"
      - "homepage.description=$HOME_DESCRIPTION"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
