version: '3.8'

services:
  grafana:
    image: grafana/grafana:10.1.0
    user: "0:0"
    environment:
      - TZ=$TZ
      - GF_AUTH_ANONYMOUS_ENABLED=$GF_AUTH_ANONYMOUS_ENABLED
      - GF_AUTH_BASIC_ENABLED=$GF_AUTH_BASIC_ENABLED
      - GF_AUTH_PROXY_ENABLED=$GF_AUTH_PROXY_ENABLED
      - GF_USERS_ALLOW_SIGN_UP=$GF_USERS_ALLOW_SIGN_UP
      - GF_INSTALL_PLUGINS=$GF_INSTALL_PLUGINS
      - GF_SERVER_ROOT_URL=$GF_SERVER_ROOT_URL
    volumes:
      - grafana_data:/var/lib/grafana
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - prometheus
    networks:
      - traefik-proxy
    configs:
      - source: docker_dashboard.json
        target: /etc/grafana/provisioning/dashboards/docker-monitoring.json
      - source: traefik_dashboard.json
        target: /etc/grafana/provisioning/dashboards/traefik_dashboard.json
      - source: grafana_dashboards.yml
        target: /etc/grafana/provisioning/dashboards/dashboards.yml
      - source: grafana_datasources.yml
        target: /etc/grafana/provisioning/datasources/datasource.yml
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-proxy"
        - "traefik.http.routers.grafana-secure.entrypoints=websecure"
        - "traefik.http.routers.grafana-secure.rule=Host(`$HOST`)"
        - "traefik.http.routers.grafana-secure.middlewares=forward-auth-verify"
        - "traefik.http.routers.grafana-secure.tls.certresolver=letsencrypt"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  redis:
    image: redis:7.2.0
    environment:
      - TZ=$TZ
      - ENABLE_OVERCOMMIT_MEMORY=true
    ports:
    - 6379:6379
    networks:
      - traefik-proxy
    deploy:
      labels:
        - "traefik.enable=false"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    ports:
      - 8987:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command: -max_procs=4 -docker_only=true
    environment:
      - TZ=$TZ
    depends_on:
      - redis
    networks:
      - traefik-proxy
    deploy:
      labels:
        - "traefik.enable=false"

  loki:
    image: grafana/loki:latest
    user: "0:0"
    ports:
      - 3100:3100
    volumes:
      - loki:/loki
    command: -config.file=/etc/loki/loki-config.yaml
    environment:
      - TZ=$TZ
    networks:
      - traefik-proxy
    configs:
      - source: loki_config.yml
        target: /etc/loki/loki-config.yaml
    deploy:
      labels:
        - "traefik.enable=false"

  promtail:
    image:  grafana/promtail:latest
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/docker-config.yaml
    environment:
      - TZ=$TZ
    depends_on:
      - loki
    networks:
      - traefik-proxy
    configs:
      - source: promtail_config.yml
        target: /etc/promtail/docker-config.yaml
    deploy:
      labels:
        - "traefik.enable=false"
        
  prometheus:
    image: prom/prometheus:v2.15.2
    user: "0:0"
    volumes:
      - prometheus:/prometheus
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - "--web.route-prefix=/"
      - "--web.external-url=https://$PROM_HOST"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    configs:
      - source: prometheus_config.yml
        target: /etc/prometheus/prometheus.yml
      - source: prometheus_alert.rules
        target: /etc/prometheus/prometheus_alert.rules
    environment:
      - TZ=$TZ
    networks:
      - traefik-proxy
    deploy:
      labels:
        - "traefik.enable=false"

volumes:
  grafana_data:
    external: true
  loki:
    external: true
  prometheus:
    external: true

configs:
  docker_dashboard.json:
    external: true
  traefik_dashboard.json:
    external: true
  grafana_dashboards.yml:
    external: true
  grafana_datasources.yml:
    external: true
  loki_config.yml:
    external: true
  prometheus_config.yml:
    external: true
  promtail_config.yml:
    external: true
  prometheus_alert.rules:
    external: true
    
networks:
  traefik-proxy:
    external: true
      
