services:
  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    domainname: ${HOST}
    ports:
      # - "8081:80/tcp" # Pi-hole web admin interface, proxied through Caddy (configure port in Caddyfile)
      # # Following are NOT proxied through Caddy, bound to host net instead:
      - "53:53"
      - "853:853/tcp" # DNS-over-TLS
    depends_on:
      - unbound
    dns:
      - 127.0.0.1
      - $MASTER_DNS
    environment:
      - TZ=$TZ
      - WEBPASSWORD=$WEBPASSWORD
      - VIRTUAL_HOST=${HOST}
      - DNS1=${UNBOUND_IP}
      - DNS2=${UNBOUND_IP}
      - DNSMASQ_USER=pihole
    volumes:
      - '$JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/etc-pihole:/etc/pihole'
      - '$JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/etc-dnsmasq.d:/etc/dnsmasq.d'
    labels:
      - "traefik.enable=true"

      ### Web UI (HTTP/HTTPS)
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=80"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://${HOST}/admin"
      - "homepage.description=$HOME_DESCRIPTION"

      ### DNS-over-TLS (853 Traefik -> 53 Pi-hole)
      # - traefik.tcp.routers.$COMPOSE_PROJECT_NAME-dot.rule=HostSNI(`$HOST`)
      # - traefik.tcp.routers.$COMPOSE_PROJECT_NAME-dot.entrypoints=dot
      # - traefik.tcp.routers.$COMPOSE_PROJECT_NAME-dot.tls.certresolver=letsencrypt
      # - traefik.tcp.routers.$COMPOSE_PROJECT_NAME-dot.service=pihole
      # - traefik.tcp.services.pihole.loadbalancer.server.port=53
      # - traefik.tcp.services.pihole.loadbalancer.proxyProtocol.version=2

  unbound:
    image: klutchell/unbound
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      default:
        ipv4_address: ${UNBOUND_IP}
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/unbound.conf:/opt/unbound/etc/unbound/unbound.conf

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
