version: '3.1'

services:
  db:
    image: postgres:12.9
    environment:
      TZ: $TZ
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME" ]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    restart: unless-stopped
    volumes:
      - ${JOHNCLOUD_ROOT}/$COMPOSE_PROJECT_NAME/db:/var/lib/postgresql/data

  keycloak:
    image: bitnami/keycloak:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - TZ=$TZ
      - KEYCLOAK_DATABASE_HOST=$COMPOSE_PROJECT_NAME-db-1
      - KEYCLOAK_USER=$KEYCLOAK_ADMIN
      - KEYCLOAK_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD
      - KEYCLOAK_DATABASE_NAME=$DB_NAME
      - KEYCLOAK_DATABASE_USER=$DB_USER
      - KEYCLOAK_DATABASE_PASSWORD=$DB_PASSWORD
      - DB_VENDOR=POSTGRES
      - PROXY_ADDRESS_FORWARDING=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.route-auth.rule=Host(`$HOST`)"
      - "traefik.http.services.route-auth.loadbalancer.server.port=8080"
      - "traefik.http.routers.route-auth.middlewares=default@file"
      - "traefik.http.routers.route-auth.entrypoints=websecure"
      - "traefik.http.routers.route-auth.tls.certresolver=letsencrypt"
      - "homepage.group=Platform"
      - "homepage.name=Keycloak"
      - "homepage.icon=keycloak.svg"
      - "homepage.href=https://$HOST/admin"
      - "homepage.description=Open Source Identity and Access Management"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
