version: "3.8"

services:
  keycloak_db:
    image: postgres:13.2
    restart: unless-stopped
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/keycloak_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_DATABASE_NAME}
      POSTGRES_USER: ${KEYCLOAK_DATABASE_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
    labels:
      - "traefik.enable=false"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    depends_on:
      - keycloak_db
    command:
      - start
      - "--features=token-exchange"
      - "--hostname-strict-https=false"
    healthcheck:
      test: ['CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/health/live']
      interval: 5s
      timeout: 5s
      retries: 30
    # ports:
    #   - 17070:8080
    environment:
      KC_PROXY_ADDRESS_FORWARDING: "true"
      KC_HEALTH_ENABLED: true
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME: $HOST
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://$COMPOSE_PROJECT_NAME-keycloak_db-1:5432/$KEYCLOAK_DATABASE_NAME?ssl=allow
      KC_DB_USERNAME: $KEYCLOAK_DATABASE_USER
      KC_DB_PASSWORD: $KEYCLOAK_DATABASE_PASSWORD
      KEYCLOAK_ADMIN: $KEYCLOAK_USER
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_PASSWORD
      PROXY_ADDRESS_FORWARDING: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`$HOST`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls.certresolver=letsencrypt"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      # # Redirect '/' to '/admin'
      # - "traefik.http.middlewares.custom-redirect.redirectregex.regex=^https:\\/\\/([^\\/]+)\\/?$$"
      # - "traefik.http.middlewares.custom-redirect.redirectregex.replacement=https://$$1/admin"
      # - "traefik.http.routers.keycloak.middlewares=default@file,custom-redirect"
      - "homepage.group=Platform"
      - "homepage.name=Keycloak"
      - "homepage.icon=keycloak.svg"
      - "homepage.href=https://$HOST/admin"
      - "homepage.description=Open Source Identity and Access Management"

  ldap:
    image: osixia/openldap:latest
    environment:
      LDAP_ORGANISATION: $LDAP_ORGANISATION
      LDAP_DOMAIN: $LDAP_DOMAIN
      LDAP_BASE_DN: ${LDAP_BASE_DN:-}
      LDAP_ADMIN_PASSWORD: $LDAP_ADMIN_PASSWORD
      LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD:-$LDAP_ADMIN_PASSWORD}
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/ldap/data:/var/lib/ldap
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/ldap/config:/etc/ldap/slapd.d
    restart: unless-stopped
    labels:
      - "traefik.enable=false"

  # Connect with cn=admin,dc=domain,dc=tld
  openldap-ui:
    image: osixia/phpldapadmin:latest
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=$COMPOSE_PROJECT_NAME-ldap-1
      - PHPLDAPADMIN_HTTPS=false
      - PHPLDAPADMIN_SERVER_PATH=/
      - PHPLDAPADMIN_TRUST_PROXY_SSL=true
    depends_on:
      - ldap
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ldap_ui.rule=Host(`ldap.$DOMAIN`)"
      - "traefik.http.routers.ldap_ui.entrypoints=websecure"
      - "traefik.http.routers.ldap_ui.tls.certresolver=letsencrypt"
      - "homepage.group=Platform"
      - "homepage.name=LDPA"
      - "homepage.icon=https://blog.raspot.in/user/pages/01.blog/installation-et-configuration-de-lldap-et-authelia-pour-limiter-lacces-a-lapplication-web-lufi/nginx-authelia-lldap-lufi.png"
      - "homepage.href=https://ldap.$DOMAIN"
      - "homepage.description=LDAP administration"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
