version: "3.8"

services:
  keycloak_db:
    image: postgres:13.2
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/keycloak_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_DATABASE_NAME}
      POSTGRES_USER: ${KEYCLOAK_DATABASE_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
    labels:
      - "traefik.enable=false"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    depends_on:
      - keycloak_db
    command:
      - start
      - "--features=token-exchange"
      - "--hostname-strict-https=false"
    healthcheck:
      test: ['CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/health/live']
      interval: 5s
      timeout: 5s
      retries: 30
    # ports:
    #   - 17070:8080
    networks:
      - backend
      - default
    environment:
      KC_PROXY_ADDRESS_FORWARDING: "true"
      KC_HEALTH_ENABLED: true
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME: $HOST
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://$COMPOSE_PROJECT_NAME-keycloak_db-1:5432/$KEYCLOAK_DATABASE_NAME?ssl=allow
      KC_DB_USERNAME: $KEYCLOAK_DATABASE_USER
      KC_DB_PASSWORD: $KEYCLOAK_DATABASE_PASSWORD
      KEYCLOAK_ADMIN: $KEYCLOAK_USER
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_PASSWORD
      PROXY_ADDRESS_FORWARDING: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`$HOST`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls.certresolver=letsencrypt"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      # # Redirect '/' to '/admin'
      # - "traefik.http.middlewares.custom-redirect.redirectregex.regex=^https:\\/\\/([^\\/]+)\\/?$$"
      # - "traefik.http.middlewares.custom-redirect.redirectregex.replacement=https://$$1/admin"
      # - "traefik.http.routers.keycloak.middlewares=default@file,custom-redirect"
      - "homepage.group=Platform"
      - "homepage.name=Keycloak"
      - "homepage.icon=keycloak.svg"
      - "homepage.href=https://$HOST/admin"
      - "homepage.description=Open Source Identity and Access Management"

  # https://github.com/lldap/lldap/blob/main/example_configs/keycloak.md
  # https://blog.raspot.in/fr/blog/installation-et-configuration-de-lldap-et-authelia-pour-limiter-lacces-a-lapplication-web-lufi
  # https://joeeey.com/blog/selfhosting-sso-with-traefik-keycloak-part-1/
  lldap:
    image: lldap/lldap:stable
    restart: unless-stopped
    # ports:
      # For LDAP
      # - "3890:3890"
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      # - "6360:6360"
      # For the web front-end
      # - "17170:17170"
    networks:
      - backend
      - default
    environment:
      - UID=$UID
      - GID=$GID
      - TZ=$TZ
      - LLDAP_JWT_SECRET=$LLDAP_JWT_SECRET
      - LLDAP_LDAP_USER_PASS=$LLDAP_LDAP_USER_PASS
      - LLDAP_LDAP_BASE_DN=$LDAP_BASE_DN
      - LLDAP_LDAPS_OPTIONS__ENABLED=true
      - LLDAP_LDAPS_OPTIONS__CERT_FILE=/certs/certificate.pem
      - LLDAP_LDAPS_OPTIONS__KEY_FILE=/certs/privatekey.pem
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/ldap/data:/data
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/ldap/secrets:/secrets
      - $JOHNCLOUD_ROOT/traefik/certs/ldaps.johncloud.fr:/certs:ro
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.ldap_ui.rule=Host(`ldap.$DOMAIN`)"
      # - "traefik.http.routers.ldap_ui.entrypoints=websecure"
      # - "traefik.http.routers.ldap_ui.tls.certresolver=letsencrypt"
      # - "traefik.http.services.ldap_ui.loadbalancer.server.port=17170"
      # - "traefik.http.routers.ldap_ui.service=ldap_ui"
      - "traefik.tcp.routers.ldaps.rule=HostSNI(`ldaps.$DOMAIN`)"
      - "traefik.tcp.routers.ldaps.entrypoints=ldaps"
      - "traefik.tcp.routers.ldaps.tls.certresolver=letsencrypt"
      - "traefik.tcp.routers.ldaps.tls.passthrough=true"
      - "traefik.tcp.services.ldaps.loadbalancer.server.port=6360"
      - "traefik.tcp.routers.ldaps.service=ldaps"
      - "homepage.group=Platform"
      - "homepage.name=LDPA"
      # - "homepage.icon="
      - "homepage.href=https://ldap.$DOMAIN"
      - "homepage.description=LDAP administration"


networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
  backend:
    driver: bridge
