version: '3.1'

services:
  db:
    image: postgres:12.9
    environment:
      TZ: $TZ
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME" ]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    restart: unless-stopped
    volumes:
      - ${JOHNCLOUD_ROOT}/$COMPOSE_PROJECT_NAME/db:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    depends_on:
      - db
    command: start
    environment:
      KC_PROXY_ADDRESS_FORWARDING: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME: $HOST
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://$COMPOSE_PROJECT_NAME-db-1:5432/$DB_NAME?ssl=allow
      KC_DB_USERNAME: $DB_USER
      KC_DB_PASSWORD: $DB_PASSWORD
      KEYCLOAK_ADMIN: $KEYCLOAK_ADMIN
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD
      PROXY_ADDRESS_FORWARDING: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.route-auth.rule=Host(`$HOST`)"
      - "traefik.http.services.route-auth.loadbalancer.server.port=8080"
      # - "traefik.http.routers.route-auth.middlewares=default@file"
      - "traefik.http.routers.route-auth.entrypoints=websecure"
      - "traefik.http.routers.route-auth.tls.certresolver=letsencrypt"
      - "homepage.group=Platform"
      - "homepage.name=Keycloak"
      - "homepage.icon=keycloak.svg"
      - "homepage.href=https://$HOST/admin"
      - "homepage.description=Open Source Identity and Access Management"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
