services:
  database:
    image: postgres
    restart: unless-stopped
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: mailman
      PGDATA: /var/lib/postgresql/data/pgdata
    labels:
      - "traefik.enable=false"

  core:
    image: maxking/mailman-core:latest
    hostname: mailman-core
    environment:
      HYPERKITTY_URL: http://$COMPOSE_PROJECT_NAME-web-1:8000/hyperkitty
      HYPERKITTY_API_KEY: $HYPERKITTY_API_KEY
      DATABASE_URL: postgres://postgres:$POSTGRES_PASSWORD@$COMPOSE_PROJECT_NAME-database-1/mailman
      DATABASE_TYPE: postgres
      DATABASE_CLASS:  mailman.database.postgresql.PostgreSQLDatabase
      # MM_HOSTNAME: $HOST
      MAILMAN_REST_PORT: 8001
      MAILMAN_ADMIN_USER: admin
      MAILMAN_ADMIN_PASS: $ADMIN_PASSWORD
      SMTP_HOST: $SMTP_HOST
      SMTP_PORT: $SMTP_PORT
    ports:
      - "8001:8001" # API
      - "8024:8024" # LMTP - incoming emails
    depends_on:
      database:
        condition: service_healthy
    
  web:
    image: maxking/mailman-web:latest
    hostname: mailman-web
    environment:
      SERVE_FROM_DOMAIN: $HOST
      HYPERKITTY_API_KEY: $HYPERKITTY_API_KEY
      MAILMAN_ADMIN_USER: admin
      MAILMAN_ADMIN_PASS: $ADMIN_PASSWORD
      SECRET_KEY: $SECRET_KEY
      DATABASE_URL: postgres://postgres:$POSTGRES_PASSWORD@$COMPOSE_PROJECT_NAME-database-1/mailman
      SMTP_HOST: $SMTP_HOST
      SMTP_PORT: $SMTP_PORT
      SMTP_HOST_USER: $SMTP_HOST_USER
      SMTP_HOST_PASSWORD: $SMTP_HOST_PASSWORD
      SMTP_USE_TLS: $SMTP_USE_TLS
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/core-data:/opt/mailman-web-data
    depends_on:
      - core
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=8000"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://$HOST"
      - "homepage.description=$HOME_DESCRIPTION"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
