version: '2'
services:
  app:
    image: machines/filestash
    restart: unless-stopped
    environment:
    - APPLICATION_URL=$HOST
    # - GDRIVE_CLIENT_ID=<gdrive_client>
    # - GDRIVE_CLIENT_SECRET=<gdrive_secret>
    # - DROPBOX_CLIENT_ID=<dropbox_key>
    - ONLYOFFICE_URL=http://$COMPOSE_PROJECT_NAME-onlyoffice-1
    # ports:
    # - "8334:8334"
    volumes:
    - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME:/app/data/state/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=8334"
      - "homepage.group=Bureautique"
      - "homepage.name=Filestash"
      - "homepage.icon=https://downloads.filestash.app/brand/logo_grey.svg"
      - "homepage.href=https://$HOST"
      - "homepage.description=File Manager"

  onlyoffice:
    image: onlyoffice/documentserver
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    labels:
      - "traefik.enable=false"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
