services:
  app:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    healthcheck:
      test: curl -fSs https://$HOST/api/healthcheck | jq -r .message || exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
    environment:
      # https://docs.linuxserver.io/images/docker-speedtest-tracker/#environment-variables-e
      - PUID=1000
      - PGID=1000
      - APP_KEY=$APP_KEY
      - ADMIN_EMAIL=$ADMIN_EMAIL
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
      - DB_CONNECTION=sqlite
      - APP_TIMEZONE=$TZ
      - DISPLAY_TIMEZONE=$TZ
      - APP_URL=https://$HOST
      - ASSET_URL=https://$HOST
      - SPEEDTEST_SCHEDULE=$SPEEDTEST_SCHEDULE
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/data:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=80"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://${HOST}/"
      - "homepage.description=$HOME_DESCRIPTION"
      - "homepage.widget.type=speedtest"
      - "homepage.widget.url=https://${HOST}"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
