services:
  app:
    image: falcosecurity/falco:latest
    restart: unless-stopped
    privileged: true
    container_name: falco
    cap_drop:
      - all
    cap_add:
      - sys_admin
      - sys_resource
      - sys_ptrace
    volumes:
      # - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/data:/config
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /proc:/host/proc:ro
      - /etc:/host/etc:ro
      - ./config/http_output.yml:/etc/falco/config.d/http_output.yml

  sidekick:
    container_name: falco-sidekick
    restart: unless-stopped
    image: falcosecurity/falcosidekick
    environment:
      WEBUI_URL: http://falco-webui:2802

  webui:
    container_name: falco-webui
    restart: unless-stopped
    image: falcosecurity/falcosidekick-ui:2.2.0
    # ports:
    #   - 2802:2802
    depends_on:
      - redis
    command: ['-r', 'redis:6379', '-d']
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=2802"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.middlewares=forward-auth-verify"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://${HOST}/"
      - "homepage.description=$HOME_DESCRIPTION"

  redis:
    restart: unless-stopped
    image: redis/redis-stack:7.2.0-v11

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
