# https://sparwan.com/articles/post/creer-votre-serveur-cloud-tuto-d-installation-de-nextcloud-via-docker-compose.html
version: '3.8'

services:
  db:
    image: mariadb:lts
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - $JOHNCLOUD_ROOT/nextcloud/db:/var/lib/mysql
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - MYSQL_ROOT_PASSWORD=$NEXTCLOUD_MYSQL_ROOT_PASSWORD # Mot de passe de l'utilisateur root de mariadb
      - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE # Nom de la base de données à créer à l'initialisation du conteneur
      - MYSQL_USER=$NEXTCLOUD_MYSQL_USER # Nom de l'utilisateur de la base de données créée
      - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD # Mot de passe de l'utilisateur créé
    labels:
      - "traefik.enable=false"

  redis:
    image: redis:latest
    restart: unless-stopped
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - $JOHNCLOUD_ROOT/nextcloud/redis:/data
    labels:
      - "traefik.enable=false"

  app:
    image: nextcloud:latest
    restart: unless-stopped
    volumes:
      - $JOHNCLOUD_ROOT/nextcloud/data:/var/www/html
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - REDIS_HOST=$COMPOSE_PROJECT_NAME-redis-1
      - MYSQL_HOST=$COMPOSE_PROJECT_NAME-db-1 # Nom du conteneur de la base de données
      - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE # Nom de la base de données
      - MYSQL_USER=$NEXTCLOUD_MYSQL_USER # Nom de l'utilisateur de la base de données
      - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD # Mot de passe de l'utilisateur de la base de données
      - SMTP_HOST=$SMTP_HOST
      - SMTP_SECURE=$SMTP_SECURE
      - SMTP_PORT=$SMTP_PORT
      - SMTP_NAME=$SMTP_NAME
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - MAIL_FROM_ADDRESS=$MAIL_FROM_ADDRESS
    depends_on:
      - db
      - redis
    labels:
      - "traefik.enable=true"
      # - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent=true"
      # - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex=https://(.*)/.well-known/(?:card|cal)dav"
      # - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement=https://$${1}/remote.php/dav"
      # - "traefik.http.middlewares.nginx.headers.referrerPolicy=no-referrer"
      # - "traefik.http.middlewares.nginx.headers.SSLRedirect=true"
      # - "traefik.http.middlewares.nginx.headers.STSSeconds=315360000"
      # - "traefik.http.middlewares.nginx.headers.browserXSSFilter=true"
      # - "traefik.http.middlewares.nginx.headers.contentTypeNosniff=true"
      # - "traefik.http.middlewares.nginx.headers.forceSTSHeader=true"
      # - "traefik.http.middlewares.nginx.headers.STSIncludeSubdomains=true"
      # - "traefik.http.middlewares.nginx.headers.STSPreload=true"
      # - "traefik.http.middlewares.nginx.headers.customFrameOptionsValue=SAMEORIGIN"
      # - "traefik.http.routers.cloud.middlewares=nextcloud_redirectregex,nginx"
      - "traefik.http.routers.cloud.rule=Host(`$HOST`)"
      - "traefik.http.routers.cloud.entrypoints=websecure"
      - "traefik.http.routers.cloud.tls.certresolver=letsencrypt"
      # - "traefik.http.services.cloud.loadbalancer.serverstransport=ignorecert"
      # - "traefik.http.services.cloud.loadbalancer.server.scheme=https"
      - "homepage.group=Bureautique"
      - "homepage.name=Nextcloud"
      - "homepage.icon=nextcloud.svg"
      - "homepage.href=https://$HOST"
      - "homepage.description=Online collaboration platform"
        
networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
    
