version: "3"

services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    environment:
      - TZ=$TZ
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/configs:/app/data/configs
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/icons:/app/public/icons
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/data:/data
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
        - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
        - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
        - "traefik.http.routers.$COMPOSE_PROJECT_NAME.middlewares=forward-auth-verify"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
