version: "2.1"

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
    volumes:
      - $JOHNCLOUD_ROOT/homepage/config:/config
    restart: unless-stopped
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
        - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
        - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
        - "traefik.http.routers.$COMPOSE_PROJECT_NAME.middlewares=forward-auth-verify"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK

