# https://www.czerniga.it/2021/11/14/how-to-install-gitlab-using-docker-compose/

version: "3.8"

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: ${RESTART_POLICY}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Email setup
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = '$ADMIN_EMAIL'
        gitlab_rails['gitlab_email_display_name'] = 'Gitlab Administrator'
        gitlab_rails['gitlab_email_reply_to'] = '$ADMIN_EMAIL'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'mail.$HOST'
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = '$ADMIN_EMAIL'
        gitlab_rails['smtp_password'] = '$ADMIN_SMTP_PASSWORD'
        gitlab_rails['smtp_domain'] = '$HOST'
        gitlab_rails['smtp_authentication'] = 'login'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['gitlab_root_email'] = '$ADMIN_EMAIL'
        # HTTPS Setup
        letsencrypt['enable'] = false
        gitlab_rails['gitlab_https'] = false
        gitlab_rails['gitlab_port'] = 80
        external_url 'https://gitlab.$HOST'
        gitlab_rails['lfs_enabled'] = true
    ports:
      - '8345:80'
      # - '8443:443'
    volumes:
      - '$JOHNCLOUD_ROOT/gitlab/config:/etc/gitlab'
      - '$JOHNCLOUD_ROOT/gitlab/logs:/var/log/gitlab'
      - '$JOHNCLOUD_ROOT/gitlab/data:/var/opt/gitlab'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`$HOST`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls.certresolver=letsencrypt"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: ${RESTART_POLICY}
    depends_on:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - '$JOHNCLOUD_ROOT/gitlab/gitlab-runner:/etc/gitlab-runner'
    labels:
      - "traefik.enable=false"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
