services:
  main:
    image: b3log/siyuan
    command: ['--workspace=/siyuan/workspace/', '--accessAuthCode=${SIYUAN_ACCESS_AUTH_CODE}']
    # ports:
    #   - 6806:6806
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/workspace:/siyuan/workspace
    restart: unless-stopped
    environment:
      # A list of time zone identifiers can be found at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=${TZ}
      - PUID=${PUID}  # Customize user ID
      - PGID=${PGID}  # Customize group ID
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=6806"

      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://${HOST}"
      - "homepage.description=$HOME_DESCRIPTION"


networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
    