version: '3.8'

name: moodle

services:
  app:
    image: docker.io/bitnami/moodle:4.1.4-debian-11-r43
    # ports:
    #   - '8090:8080'
    restart: unless-stopped
    networks:
      - moodle-network
      - default
    environment:
      - TZ=$TZ
      - MOODLE_DATABASE_HOST=$DB_HOST
      - MOODLE_DATABASE_PORT_NUMBER=$DB_PORT_NUMBER
      - MOODLE_DATABASE_USER=$DB_USER
      - MOODLE_DATABASE_NAME=$DB_NAME
      - MOODLE_DATABASE_PASSWORD=$DB_PASSWORD
    volumes:
      - $JOHNCLOUD_ROOT/moodle/data:/bitnami/moodle
      - $JOHNCLOUD_ROOT/moodle/moodledata:/bitnami/moodledata
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moodle.rule=Host(`$HOST`)"
      - "traefik.http.routers.moodle.entrypoints=websecure"
      - "traefik.http.routers.moodle.tls.certresolver=letsencrypt"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://$HOST"
      - "homepage.description=$HOME_DESCRIPTION"

  db:
    image: mariadb:lts
    restart: unless-stopped
    networks:
      - moodle-network
    environment:
      - TZ=$TZ
      - MARIADB_PASSWORD=$DB_PASSWORD
      - MARIADB_USER=$DB_USER
      - MARIADB_DATABASE=$DB_NAME
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - MARIADB_RANDOM_ROOT_PASSWORD=$DB_RANDOM_ROOT_PASSWORD
    volumes:
      - $JOHNCLOUD_ROOT/moodle/db:/var/lib/mysql
    labels:
      - "traefik.enable=false"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
  backend:
    name: moodle-network
    
