services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/qdrant_data:/qdrant/storage
      - $JOHNCLOUD_ROOT/traefik/certs/$HOST:/tls:ro
    environment:
      - QDRANT__SERVICE__API_KEY=$QDRANT_API_KEY
      - QDRANT__SERVICE__ENABLE_TLS=true
      - QDRANT__TLS__CERT=/tls/cert.pem
      - QDRANT__TLS__KEY=/tls/key.pem
    ports:
      - 6333:6333
      - 6334:6334
    labels:
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME - Qdrant"
      - "homepage.icon=https://avatars.githubusercontent.com/u/73504361"
      - "homepage.href=https://$HOST:6333/dashboard"
      - "homepage.description=$HOME_DESCRIPTION"
      - pangolin.public-resources.${COMPOSE_PROJECT_NAME}-qdrant.name=${COMPOSE_PROJECT_NAME}-qdrant
      - pangolin.public-resources.${COMPOSE_PROJECT_NAME}-qdrant.full-domain=$HOST
      - pangolin.public-resources.${COMPOSE_PROJECT_NAME}-qdrant.protocol=http
      - pangolin.public-resources.${COMPOSE_PROJECT_NAME}-qdrant.ssl=true

  ragindexer:
    image: ydethe/ragindexer:latest
    restart: unless-stopped
    depends_on:
      - qdrant
    volumes:
      - $DOCUMENTS_ROOT_FOLDER:/docs:ro
    environment:
      - LOGLEVEL=$LOGLEVEL
      - SCAN_ROOT=/docs
      - EMBEDDING_MODEL=$EMBEDDING_MODEL
      - EMBEDDING_MODEL_TRUST_REMOTE_CODE=false
      - CHUNK_SIZE=$CHUNK_SIZE
      - OVERLAP_SIZE=$OVERLAP_SIZE
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY=$QDRANT_API_KEY

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
    