version: '3'

services:
  db:
    image: postgres:12.9
    environment:
      POSTGRES_DB: fusionauth
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - ${JOHNCLOUD_ROOT}/fusionauth/db_data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      cluster.name: fusionauth
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
    healthcheck:
      test: [ "CMD", "curl",  "--fail" ,"--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://localhost:9200/" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${JOHNCLOUD_ROOT}/fusionauth/search/logs:/usr/share/elasticsearch/logs/
      - ${JOHNCLOUD_ROOT}/fusionauth/search/data:/usr/share/elasticsearch/data/
    labels:
      - "traefik.enable=false"

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      db:
        condition: service_healthy
      search:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://$COMPOSE_PROJECT_NAME-db-1:5432/fusionauth
      DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: production
      FUSIONAUTH_APP_URL: https://$HOST
      SEARCH_SERVERS: http://$COMPOSE_PROJECT_NAME-search-1:9200
      SEARCH_TYPE: elasticsearch
    restart: unless-stopped
    # ports:
    #   - 9011:9011
    # volumes:
      # - ${JOHNCLOUD_ROOT}/fusionauth/fusionauth/config:/usr/local/fusionauth/config:rw
      # - ${JOHNCLOUD_ROOT}/fusionauth/fusionauth/logs:/usr/local/fusionauth/logs:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fusionauth.rule=Host(`$HOST`)"
      - "traefik.http.routers.fusionauth.entrypoints=websecure"
      - "traefik.http.routers.fusionauth.tls.certresolver=letsencrypt"
      - "traefik.http.services.fusionauth.loadbalancer.server.port=9011"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
