version: '3'

services:
  ldap:
    image: quay.io/389ds/dirsrv:latest
    restart: unless-stopped
    # Optionally uncomment one or both ports to expose to the host
    # ports:
    #   - '389:3389/tcp'    # Unencrypted port
    #   - '636:3636/tcp'    # SSL/TLS port 
    environment:
      DS_DM_PASSWORD: $LDAP_ADMIN_PASSWORD
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/ldap:/data
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.ldap.rule=Host(`ldap.$DOMAIN`)"
    #   - "traefik.http.routers.ldap.entrypoints=ldaps"
    #   - "traefik.http.routers.ldap.tls.certresolver=letsencrypt"

  db:
    image: postgres:12.9
    environment:
      POSTGRES_DB: fusionauth
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - ${JOHNCLOUD_ROOT}/$COMPOSE_PROJECT_NAME/db_data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      cluster.name: fusionauth
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
    healthcheck:
      test: [ "CMD", "curl",  "--fail" ,"--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://localhost:9200/" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${JOHNCLOUD_ROOT}/$COMPOSE_PROJECT_NAME/search/logs:/usr/share/elasticsearch/logs/
      - ${JOHNCLOUD_ROOT}/$COMPOSE_PROJECT_NAME/search/data:/usr/share/elasticsearch/data/
    labels:
      - "traefik.enable=false"

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      db:
        condition: service_healthy
      search:
        condition: service_healthy
      ldap:
        condition: service_started
    environment:
      DATABASE_URL: jdbc:postgresql://$COMPOSE_PROJECT_NAME-db-1:5432/fusionauth
      DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: production
      FUSIONAUTH_APP_URL: https://$HOST
      SEARCH_SERVERS: http://$COMPOSE_PROJECT_NAME-search-1:9200
      SEARCH_TYPE: elasticsearch
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fusionauth.rule=Host(`$HOST`)"
      - "traefik.http.routers.fusionauth.entrypoints=websecure"
      - "traefik.http.routers.fusionauth.tls.certresolver=letsencrypt"
      - "traefik.http.services.fusionauth.loadbalancer.server.port=9011"
      - "homepage.group=Platform"
      - "homepage.name=FusionAuth"
      - "homepage.icon=https://www.vectorlogo.zone/logos/fusionauthio/fusionauthio-icon.svg"
      - "homepage.href=https://$HOST"
      - "homepage.description=Authentication & Authorization"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
