services:
  app:
    image: permitio/pdp-v2:latest
    restart: unless-stopped
    environment:
      - PDP_ORG_API_KEY=$PDP_ORG_API_KEY
      - PDP_ACTIVE_PROJECT=$PDP_ACTIVE_PROJECT
      - PDP_ACTIVE_ENV=$PDP_ACTIVE_ENV
      - PDP_DEBUG=PDP_DEBUG
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=7000"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://${HOST}"
      - "homepage.description=$HOME_DESCRIPTION"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
