version: '3.1'

services:
  app:
    image: ghcr.io/tailscale/tailscale:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - VIRTUAL_HOST=${HOST}
      - TS_ACCEPT_DNS=$TS_ACCEPT_DNS
      - TS_AUTH_ONCE=$TS_AUTH_ONCE
      - TS_AUTHKEY=$TS_AUTHKEY
      - TS_DEST_IP=$TS_DEST_IP
      - TS_HOSTNAME=$TS_HOSTNAME
      - TS_OUTBOUND_HTTP_PROXY_LISTEN=$TS_OUTBOUND_HTTP_PROXY_LISTEN
      - TS_ROUTES=$TS_ROUTES
      - TS_SOCKET=$TS_SOCKET
      - TS_SOCKS5_SERVER=$TS_SOCKS5_SERVER
      - TS_USERSPACE=$TS_USERSPACE
      - TS_STATE_DIR=$TS_STATE_DIR
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    labels:
      - "traefik.enable=false"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
