services:
  server:
    image: adguard/adguardhome
    restart: unless-stopped
    volumes:
    - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/work:/opt/adguardhome/work
    - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/config:/opt/adguardhome/conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME-install.rule=Host(`install.$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME-install.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME-install.tls.certresolver=letsencrypt"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME-install.service=$COMPOSE_PROJECT_NAME-install"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME-install.loadbalancer.server.port=3000"

      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.service=$COMPOSE_PROJECT_NAME"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=80"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://${HOST}/"
      - "homepage.description=$HOME_DESCRIPTION"

      - traefik.tcp.routers.$COMPOSE_PROJECT_NAME-dns.rule=HostSNI(`*`)
      - traefik.tcp.routers.$COMPOSE_PROJECT_NAME-dns.tls=false
      - traefik.tcp.routers.$COMPOSE_PROJECT_NAME-dns.entrypoints=dns
      - traefik.tcp.routers.$COMPOSE_PROJECT_NAME-dns.service=$COMPOSE_PROJECT_NAME-dns
      - traefik.tcp.services.$COMPOSE_PROJECT_NAME-dns.loadbalancer.server.port=53


networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
