version: '3.1'

services:
  app:
    image: lscr.io/linuxserver/jellyfin:latest
    volumes:
      - $JOHNCLOUD_ROOT/jellyfin/config:/config
      - $JOHNCLOUD_ROOT/nextcloud/data/data/ydethe/files/Musique:/data:ro
    restart: unless-stopped
    ports:
      - 8096:8096
      - 8920:8920 #optional
    environment:
      - PUID=$USERID
      - PGID=$GROUPID
      - TZ=$TZ
    # Optional - alternative address used for autodiscovery
    #   - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`$HOST`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "homepage.group=Media"
      - "homepage.name=Jellyfin"
      - "homepage.icon=https://raw.githubusercontent.com/jellyfin/jellyfin-ux/master/branding/SVG/icon-transparent-vue.svg"
      - "homepage.href=https://$HOST"
      - "homepage.description=Jellyfin media server"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
    