services:
  server:
    image: ydethe/forward-proxy
    restart: unless-stopped
    ports:
    - 3128:3128
    volumes:
    - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/config:/etc/nginx/conf.d:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=web"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
