services:
  server:
    image: ydethe/forward-proxy:main
    restart: unless-stopped
    volumes:
    - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/config:/etc/nginx/conf.d:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls=false"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=web"

      - traefik.tcp.routers.$COMPOSE_PROJECT_NAME-prox.rule=HostSNI(`*`)
      - traefik.tcp.routers.$COMPOSE_PROJECT_NAME-prox.tls=false
      - traefik.tcp.routers.$COMPOSE_PROJECT_NAME-prox.entrypoints=proxy
      - traefik.tcp.routers.$COMPOSE_PROJECT_NAME-prox.service=$COMPOSE_PROJECT_NAME-prox
      - traefik.tcp.services.$COMPOSE_PROJECT_NAME-prox.loadbalancer.server.port=3128

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
