services:
  netdata:
    image: netdata/netdata:stable
    restart: unless-stopped
    # pid: host
    # network_mode: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/config:/etc/netdata
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/lib:/var/lib/netdata
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/hostname:/host/etc/hostname:ro
      - /proc:/host/proc:ro
      - /run/dbus:/run/dbus:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NETDATA_CLAIM_TOKEN=$NETDATA_CLAIM_TOKEN
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=$NETDATA_CLAIM_ROOMS
    labels:
      - "traefik.enable=false"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=$HOME_LINK"
      - "homepage.description=$HOME_DESCRIPTION"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK

      