services:
  # https://github.com/dirtsimple/poste.io
  posteio:
    image: analogic/poste.io
    restart: unless-stopped
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/data:/data
    environment:
      TZ: $TZ
      HTTPS: OFF
      HTTP_PORT: 8534
      DISABLE_CLAMAV: $DISABLE_CLAMAV
      DISABLE_RSPAMD: $DISABLE_RSPAMD
      DISABLE_ROUNDCUBE: $DISABLE_ROUNDCUBE
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=8534"

      # TCP Routers for Email Protocols
      # SMTP (Port 25)
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-smtp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-smtp.entrypoints=smtp"
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-smtp.service=$COMPOSE_PROJECT_NAME-smtp"
      - "traefik.tcp.services.$COMPOSE_PROJECT_NAME-smtp.loadbalancer.server.port=25"
      
      # IMAP (Port 143)
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-imap.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-imap.entrypoints=imap"
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-imap.service=$COMPOSE_PROJECT_NAME-imap"
      - "traefik.tcp.services.$COMPOSE_PROJECT_NAME-imap.loadbalancer.server.port=143"
      
      # POP3 (Port 110)
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-pop3.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-pop3.entrypoints=pop3"
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-pop3.service=$COMPOSE_PROJECT_NAME-pop3"
      - "traefik.tcp.services.$COMPOSE_PROJECT_NAME-pop3.loadbalancer.server.port=110"

      # SMTPS (Port 465)
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-smtps.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-smtps.entrypoints=smtps"
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-smtps.service=$COMPOSE_PROJECT_NAME-smtps"
      - "traefik.tcp.services.$COMPOSE_PROJECT_NAME-smtps.loadbalancer.server.port=465"

      # IMAPS (Port 993)
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-imaps.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-imaps.entrypoints=imaps"
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-imaps.service=$COMPOSE_PROJECT_NAME-imaps"
      - "traefik.tcp.services.$COMPOSE_PROJECT_NAME-imaps.loadbalancer.server.port=993"

      # POP3S (Port 995)
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-pop3s.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-pop3s.entrypoints=pop3s"
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-pop3s.service=$COMPOSE_PROJECT_NAME-pop3s"
      - "traefik.tcp.services.$COMPOSE_PROJECT_NAME-pop3s.loadbalancer.server.port=995"

      # Submission (Port 587)
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-msa.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-msa.entrypoints=msa"
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-msa.service=$COMPOSE_PROJECT_NAME-msa"
      - "traefik.tcp.services.$COMPOSE_PROJECT_NAME-msa.loadbalancer.server.port=587"

      # Homepage settings
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://$HOST/admin"
      - "homepage.description=$HOME_DESCRIPTION"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
    