# https://hub.docker.com/r/linuxserver/code-server

version: "2.1"

services:
  app:
    image: lscr.io/linuxserver/code-server:4.16.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
    volumes:
      - $JOHNCLOUD_ROOT/vscode/workspace_data:/config
    ports:
      - 8741:8443
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code.rule=Host(`$HOST`)"
      - "traefik.http.routers.code.entrypoints=websecure"
      - "traefik.http.routers.code.tls.certresolver=letsencrypt"

networks:
  default:
    external: true
    name: traefik-proxy
    
