version: "3"

services:
  whoami:
    image: traefik/whoami:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forward.rule=Host(`whoami.$HOST`)"   
      - "traefik.http.routers.forward.entrypoints=websecure"
      - "traefik.http.routers.forward.tls.certresolver=letsencrypt"

networks:
  default:
    external: true
    name: traefik-proxy
    
