certificate.default.cert = "%{file:/data/certs/mail.domain.tld/cert.pem}%"
certificate.default.default = true
certificate.default.private-key = "%{file:/data/certs/mail.domain.tld/key.pem}%"
directory.internal.store = "rocksdb"
directory.internal.type = "internal"
lookup.default.hostname = "mail.domain.tld"
server.listener.http.bind = "[::]:8080"
server.listener.http.protocol = "http"
server.listener.https.bind = "[::]:443"
server.listener.https.protocol = "http"
server.listener.https.tls.implicit = true
server.listener.imap.bind = "[::]:143"
server.listener.imap.protocol = "imap"
server.listener.imap.proxy.override = true
server.listener.imap.proxy.trusted-networks.0 = "192.168.203.0/16"
server.listener.imap.proxy.trusted-networks.1 = "192.168.203.100"
server.listener.imaptls.bind = "[::]:993"
server.listener.imaptls.protocol = "imap"
server.listener.imaptls.tls.implicit = true
server.listener.imaptls.proxy.override = true
server.listener.imaptls.proxy.trusted-networks.0 = "192.168.203.0/16"
server.listener.imaptls.proxy.trusted-networks.1 = "192.168.203.100"
server.listener.pop3.bind = "[::]:110"
server.listener.pop3.protocol = "pop3"
server.listener.pop3.proxy.override = true
server.listener.pop3.proxy.trusted-networks.0 = "192.168.203.0/16"
server.listener.pop3.proxy.trusted-networks.1 = "192.168.203.100"
server.listener.pop3s.bind = "[::]:995"
server.listener.pop3s.protocol = "pop3"
server.listener.pop3s.tls.implicit = true
server.listener.pop3s.proxy.override = true
server.listener.pop3s.proxy.trusted-networks.0 = "192.168.203.0/16"
server.listener.pop3s.proxy.trusted-networks.1 = "192.168.203.100"
server.listener.sieve.bind = "[::]:4190"
server.listener.sieve.protocol = "managesieve"
server.listener.sieve.proxy.override = true
server.listener.sieve.proxy.trusted-networks.0 = "192.168.203.0/16"
server.listener.sieve.proxy.trusted-networks.1 = "192.168.203.100"
server.listener.smtp.bind = "[::]:25"
server.listener.smtp.protocol = "smtp"
server.listener.smtp.proxy.override = true
server.listener.smtp.proxy.trusted-networks.0 = "192.168.203.0/16"
server.listener.smtp.proxy.trusted-networks.1 = "192.168.203.100"
server.listener.submission.bind = "[::]:587"
server.listener.submission.protocol = "smtp"
server.listener.submission.proxy.override = true
server.listener.submission.proxy.trusted-networks.0 = "192.168.203.0/16"
server.listener.submission.proxy.trusted-networks.1 = "192.168.203.100"
server.listener.submissions.bind = "[::]:465"
server.listener.submissions.protocol = "smtp"
server.listener.submissions.tls.implicit = true
server.listener.submissions.proxy.override = true
server.listener.submissions.proxy.trusted-networks.0 = "192.168.203.0/16"
server.listener.submissions.proxy.trusted-networks.1 = "172.19.0.2"
storage.blob = "rocksdb"
storage.data = "rocksdb"
storage.directory = "internal"
storage.fts = "rocksdb"
storage.lookup = "rocksdb"
store.rocksdb.compression = "lz4"
store.rocksdb.path = "/opt/stalwart-mail/data"
store.rocksdb.type = "rocksdb"
tracer.log.ansi = false
tracer.log.buffered = true
tracer.log.enable = true
tracer.log.level = "info"
tracer.log.lossy = false
tracer.log.multiline = false
tracer.log.type = "stdout"
