services: 
  nocodb: 
    depends_on: 
      - nocodb-db
    environment: 
      - "NC_DB=pg://nocodb-db:5432?u=${DATABASE_USER}&p=${DATABASE_PW}&d=${DATABASE_NAME}"
      - "NC_PUBLIC_URL=https://$HOST"
      - NC_DISABLE_TELE=true
    image: "nocodb/nocodb:latest"
    labels: 
      - traefik.enable=true
      - traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=8080
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`${HOST}`)"
      - traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://$HOST"
      - "homepage.description=$HOME_DESCRIPTION"
    restart: unless-stopped
    volumes: 
      - "$JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/data:/usr/app/data"

  nocodb-db: 
    environment: 
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_PASSWORD: "${DATABASE_PW}"
      POSTGRES_USER: "${DATABASE_USER}"
    healthcheck: 
      interval: 10s
      retries: 10
      test: "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"
      timeout: 2s
    image: "postgres:12.17-alpine"
    restart: unless-stopped
    volumes: 
      - "$JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/db:/var/lib/postgresql/data"
      
networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
    