version: '2.2'

services:
  # External dependencies
  redis:
    image: redis:7.2.0-alpine
    restart: unless-stopped
    container_name: redis
    volumes:
      - "$JOHNCLOUD_ROOT/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - "traefik.enable=false"

  # Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    container_name: front
    environment:
      - ADMIN=$ADMIN
      - ANTIVIRUS=$ANTIVIRUS
      - API=$API
      - API_TOKEN=$API_TOKEN
      - AUTH_RATELIMIT_IP=$AUTH_RATELIMIT_IP
      - AUTH_RATELIMIT_USER=$AUTH_RATELIMIT_USER
      - COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME
      - COMPRESSION=$COMPRESSION
      - COMPRESSION_LEVEL=$COMPRESSION_LEVEL
      - CREDENTIAL_ROUNDS=$CREDENTIAL_ROUNDS
      - DEFAULT_SPAM_THRESHOLD=$DEFAULT_SPAM_THRESHOLD
      - DISABLE_STATISTICS=$DISABLE_STATISTICS
      - DMARC_RUA=$DMARC_RUA
      - DMARC_RUF=$DMARC_RUF
      - DOMAIN=$DOMAIN
      - FETCHMAIL_DELAY=$FETCHMAIL_DELAY
      - FETCHMAIL_ENABLED=$FETCHMAIL_ENABLED
      - HOSTNAMES=$HOSTNAMES
      - INITIAL_ADMIN_ACCOUNT=$INITIAL_ADMIN_ACCOUNT
      - INITIAL_ADMIN_DOMAIN=$INITIAL_ADMIN_DOMAIN
      - INITIAL_ADMIN_MODE=$INITIAL_ADMIN_MODE
      - INITIAL_ADMIN_PW=$INITIAL_ADMIN_PW
      - LOG_LEVEL=$LOG_LEVEL
      - MESSAGE_RATELIMIT=$MESSAGE_RATELIMIT
      - MESSAGE_SIZE_LIMIT=$MESSAGE_SIZE_LIMIT
      - POSTMASTER=$POSTMASTER
      - REAL_IP_FROM=$REAL_IP_FROM
      - REAL_IP_HEADER=$REAL_IP_HEADER
      - RECIPIENT_DELIMITER=$RECIPIENT_DELIMITER
      - REJECT_UNLISTED_RECIPIENT=$REJECT_UNLISTED_RECIPIENT
      - RELAYHOST=$RELAYHOST
      - RELAYNETS=$RELAYNETS
      - SCAN_MACROS=$SCAN_MACROS
      - SECRET_KEY=$SECRET_KEY
      - SITENAME=$SITENAME
      - SUBNET=$SUBNET
      - TLS_FLAVOR=$TLS_FLAVOR
      - TZ=$TZ
      - WEB_ADMIN=$WEB_ADMIN
      - WEB_API=$WEB_API
      - WEB_WEBMAIL=$WEB_WEBMAIL
      - WEBDAV=$WEBDAV
      - WEBMAIL=$WEBMAIL
      - WEBROOT_REDIRECT=$WEBROOT_REDIRECT
      - WEBSITE=$WEBSITE
      - WELCOME=$WELCOME
      - WELCOME_BODY=$WELCOME_BODY
      - WELCOME_SUBJECT=$WELCOME_SUBJECT
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "$REAL_IP_FROM:25:25"
      - "$REAL_IP_FROM:465:465"
      - "$REAL_IP_FROM:587:587"
      - "$REAL_IP_FROM:110:110"
      - "$REAL_IP_FROM:995:995"
      - "$REAL_IP_FROM:143:143"
      - "$REAL_IP_FROM:993:993"
    networks:
      - default
    volumes:
      - $JOHNCLOUD_ROOT/mailu/overrides/nginx:/overrides:ro
      - $JOHNCLOUD_ROOT/traefik/certs/$TRAEFIK_DOMAIN/certificate.pem:/certs/cert.pem
      - $JOHNCLOUD_ROOT/traefik/certs/$TRAEFIK_DOMAIN/privatekey.pem:/certs/key.pem
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`$TRAEFIK_DOMAIN`)"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.routers.front.tls.certresolver=letsencrypt"
      - "traefik.http.routers.front.service=mailu-websecure-svc"
      - "traefik.http.services.mailu-websecure-svc.loadbalancer.server.port=80"

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    environment:
      - ADMIN=$ADMIN
      - ANTIVIRUS=$ANTIVIRUS
      - API=$API
      - API_TOKEN=$API_TOKEN
      - AUTH_RATELIMIT_IP=$AUTH_RATELIMIT_IP
      - AUTH_RATELIMIT_USER=$AUTH_RATELIMIT_USER
      - COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME
      - COMPRESSION=$COMPRESSION
      - COMPRESSION_LEVEL=$COMPRESSION_LEVEL
      - CREDENTIAL_ROUNDS=$CREDENTIAL_ROUNDS
      - DEFAULT_SPAM_THRESHOLD=$DEFAULT_SPAM_THRESHOLD
      - DISABLE_STATISTICS=$DISABLE_STATISTICS
      - DMARC_RUA=$DMARC_RUA
      - DMARC_RUF=$DMARC_RUF
      - DOMAIN=$DOMAIN
      - FETCHMAIL_DELAY=$FETCHMAIL_DELAY
      - FETCHMAIL_ENABLED=$FETCHMAIL_ENABLED
      - HOSTNAMES=$HOSTNAMES
      - INITIAL_ADMIN_ACCOUNT=$INITIAL_ADMIN_ACCOUNT
      - INITIAL_ADMIN_DOMAIN=$INITIAL_ADMIN_DOMAIN
      - INITIAL_ADMIN_MODE=$INITIAL_ADMIN_MODE
      - INITIAL_ADMIN_PW=$INITIAL_ADMIN_PW
      - LOG_LEVEL=$LOG_LEVEL
      - MESSAGE_RATELIMIT=$MESSAGE_RATELIMIT
      - MESSAGE_SIZE_LIMIT=$MESSAGE_SIZE_LIMIT
      - POSTMASTER=$POSTMASTER
      - REAL_IP_FROM=$REAL_IP_FROM
      - REAL_IP_HEADER=$REAL_IP_HEADER
      - RECIPIENT_DELIMITER=$RECIPIENT_DELIMITER
      - REJECT_UNLISTED_RECIPIENT=$REJECT_UNLISTED_RECIPIENT
      - RELAYHOST=$RELAYHOST
      - RELAYNETS=$RELAYNETS
      - SCAN_MACROS=$SCAN_MACROS
      - SECRET_KEY=$SECRET_KEY
      - SITENAME=$SITENAME
      - SUBNET=$SUBNET
      - TLS_FLAVOR=$TLS_FLAVOR
      - TZ=$TZ
      - WEB_ADMIN=$WEB_ADMIN
      - WEB_API=$WEB_API
      - WEB_WEBMAIL=$WEB_WEBMAIL
      - WEBDAV=$WEBDAV
      - WEBMAIL=$WEBMAIL
      - WEBROOT_REDIRECT=$WEBROOT_REDIRECT
      - WEBSITE=$WEBSITE
      - WELCOME=$WELCOME
      - WELCOME_BODY=$WELCOME_BODY
      - WELCOME_SUBJECT=$WELCOME_SUBJECT
    container_name: resolver
    networks:
      default:
        ipv4_address: 192.168.203.254
    labels:
      - "traefik.enable=false"

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    container_name: admin
    environment:
      - ADMIN=$ADMIN
      - ANTIVIRUS=$ANTIVIRUS
      - API=$API
      - API_TOKEN=$API_TOKEN
      - AUTH_RATELIMIT_IP=$AUTH_RATELIMIT_IP
      - AUTH_RATELIMIT_USER=$AUTH_RATELIMIT_USER
      - COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME
      - COMPRESSION=$COMPRESSION
      - COMPRESSION_LEVEL=$COMPRESSION_LEVEL
      - CREDENTIAL_ROUNDS=$CREDENTIAL_ROUNDS
      - DEFAULT_SPAM_THRESHOLD=$DEFAULT_SPAM_THRESHOLD
      - DISABLE_STATISTICS=$DISABLE_STATISTICS
      - DMARC_RUA=$DMARC_RUA
      - DMARC_RUF=$DMARC_RUF
      - DOMAIN=$DOMAIN
      - FETCHMAIL_DELAY=$FETCHMAIL_DELAY
      - FETCHMAIL_ENABLED=$FETCHMAIL_ENABLED
      - HOSTNAMES=$HOSTNAMES
      - INITIAL_ADMIN_ACCOUNT=$INITIAL_ADMIN_ACCOUNT
      - INITIAL_ADMIN_DOMAIN=$INITIAL_ADMIN_DOMAIN
      - INITIAL_ADMIN_MODE=$INITIAL_ADMIN_MODE
      - INITIAL_ADMIN_PW=$INITIAL_ADMIN_PW
      - LOG_LEVEL=$LOG_LEVEL
      - MESSAGE_RATELIMIT=$MESSAGE_RATELIMIT
      - MESSAGE_SIZE_LIMIT=$MESSAGE_SIZE_LIMIT
      - POSTMASTER=$POSTMASTER
      - REAL_IP_FROM=$REAL_IP_FROM
      - REAL_IP_HEADER=$REAL_IP_HEADER
      - RECIPIENT_DELIMITER=$RECIPIENT_DELIMITER
      - REJECT_UNLISTED_RECIPIENT=$REJECT_UNLISTED_RECIPIENT
      - RELAYHOST=$RELAYHOST
      - RELAYNETS=$RELAYNETS
      - SCAN_MACROS=$SCAN_MACROS
      - SECRET_KEY=$SECRET_KEY
      - SITENAME=$SITENAME
      - SUBNET=$SUBNET
      - TLS_FLAVOR=$TLS_FLAVOR
      - TZ=$TZ
      - WEB_ADMIN=$WEB_ADMIN
      - WEB_API=$WEB_API
      - WEB_WEBMAIL=$WEB_WEBMAIL
      - WEBDAV=$WEBDAV
      - WEBMAIL=$WEBMAIL
      - WEBROOT_REDIRECT=$WEBROOT_REDIRECT
      - WEBSITE=$WEBSITE
      - WELCOME=$WELCOME
      - WELCOME_BODY=$WELCOME_BODY
      - WELCOME_SUBJECT=$WELCOME_SUBJECT
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "$JOHNCLOUD_ROOT/mailu/data:/data"
      - "$JOHNCLOUD_ROOT/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - "traefik.enable=false"

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    container_name: imap
    environment:
      - ADMIN=$ADMIN
      - ANTIVIRUS=$ANTIVIRUS
      - API=$API
      - API_TOKEN=$API_TOKEN
      - AUTH_RATELIMIT_IP=$AUTH_RATELIMIT_IP
      - AUTH_RATELIMIT_USER=$AUTH_RATELIMIT_USER
      - COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME
      - COMPRESSION=$COMPRESSION
      - COMPRESSION_LEVEL=$COMPRESSION_LEVEL
      - CREDENTIAL_ROUNDS=$CREDENTIAL_ROUNDS
      - DEFAULT_SPAM_THRESHOLD=$DEFAULT_SPAM_THRESHOLD
      - DISABLE_STATISTICS=$DISABLE_STATISTICS
      - DMARC_RUA=$DMARC_RUA
      - DMARC_RUF=$DMARC_RUF
      - DOMAIN=$DOMAIN
      - FETCHMAIL_DELAY=$FETCHMAIL_DELAY
      - FETCHMAIL_ENABLED=$FETCHMAIL_ENABLED
      - HOSTNAMES=$HOSTNAMES
      - INITIAL_ADMIN_ACCOUNT=$INITIAL_ADMIN_ACCOUNT
      - INITIAL_ADMIN_DOMAIN=$INITIAL_ADMIN_DOMAIN
      - INITIAL_ADMIN_MODE=$INITIAL_ADMIN_MODE
      - INITIAL_ADMIN_PW=$INITIAL_ADMIN_PW
      - LOG_LEVEL=$LOG_LEVEL
      - MESSAGE_RATELIMIT=$MESSAGE_RATELIMIT
      - MESSAGE_SIZE_LIMIT=$MESSAGE_SIZE_LIMIT
      - POSTMASTER=$POSTMASTER
      - REAL_IP_FROM=$REAL_IP_FROM
      - REAL_IP_HEADER=$REAL_IP_HEADER
      - RECIPIENT_DELIMITER=$RECIPIENT_DELIMITER
      - REJECT_UNLISTED_RECIPIENT=$REJECT_UNLISTED_RECIPIENT
      - RELAYHOST=$RELAYHOST
      - RELAYNETS=$RELAYNETS
      - SCAN_MACROS=$SCAN_MACROS
      - SECRET_KEY=$SECRET_KEY
      - SITENAME=$SITENAME
      - SUBNET=$SUBNET
      - TLS_FLAVOR=$TLS_FLAVOR
      - TZ=$TZ
      - WEB_ADMIN=$WEB_ADMIN
      - WEB_API=$WEB_API
      - WEB_WEBMAIL=$WEB_WEBMAIL
      - WEBDAV=$WEBDAV
      - WEBMAIL=$WEBMAIL
      - WEBROOT_REDIRECT=$WEBROOT_REDIRECT
      - WEBSITE=$WEBSITE
      - WELCOME=$WELCOME
      - WELCOME_BODY=$WELCOME_BODY
      - WELCOME_SUBJECT=$WELCOME_SUBJECT
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "$JOHNCLOUD_ROOT/mailu/mail:/mail"
      - "$JOHNCLOUD_ROOT/mailu/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - "traefik.enable=false"

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    container_name: smtp
    environment:
      - ADMIN=$ADMIN
      - ANTIVIRUS=$ANTIVIRUS
      - API=$API
      - API_TOKEN=$API_TOKEN
      - AUTH_RATELIMIT_IP=$AUTH_RATELIMIT_IP
      - AUTH_RATELIMIT_USER=$AUTH_RATELIMIT_USER
      - COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME
      - COMPRESSION=$COMPRESSION
      - COMPRESSION_LEVEL=$COMPRESSION_LEVEL
      - CREDENTIAL_ROUNDS=$CREDENTIAL_ROUNDS
      - DEFAULT_SPAM_THRESHOLD=$DEFAULT_SPAM_THRESHOLD
      - DISABLE_STATISTICS=$DISABLE_STATISTICS
      - DMARC_RUA=$DMARC_RUA
      - DMARC_RUF=$DMARC_RUF
      - DOMAIN=$DOMAIN
      - FETCHMAIL_DELAY=$FETCHMAIL_DELAY
      - FETCHMAIL_ENABLED=$FETCHMAIL_ENABLED
      - HOSTNAMES=$HOSTNAMES
      - INITIAL_ADMIN_ACCOUNT=$INITIAL_ADMIN_ACCOUNT
      - INITIAL_ADMIN_DOMAIN=$INITIAL_ADMIN_DOMAIN
      - INITIAL_ADMIN_MODE=$INITIAL_ADMIN_MODE
      - INITIAL_ADMIN_PW=$INITIAL_ADMIN_PW
      - LOG_LEVEL=$LOG_LEVEL
      - MESSAGE_RATELIMIT=$MESSAGE_RATELIMIT
      - MESSAGE_SIZE_LIMIT=$MESSAGE_SIZE_LIMIT
      - POSTMASTER=$POSTMASTER
      - REAL_IP_FROM=$REAL_IP_FROM
      - REAL_IP_HEADER=$REAL_IP_HEADER
      - RECIPIENT_DELIMITER=$RECIPIENT_DELIMITER
      - REJECT_UNLISTED_RECIPIENT=$REJECT_UNLISTED_RECIPIENT
      - RELAYHOST=$RELAYHOST
      - RELAYNETS=$RELAYNETS
      - SCAN_MACROS=$SCAN_MACROS
      - SECRET_KEY=$SECRET_KEY
      - SITENAME=$SITENAME
      - SUBNET=$SUBNET
      - TLS_FLAVOR=$TLS_FLAVOR
      - TZ=$TZ
      - WEB_ADMIN=$WEB_ADMIN
      - WEB_API=$WEB_API
      - WEB_WEBMAIL=$WEB_WEBMAIL
      - WEBDAV=$WEBDAV
      - WEBMAIL=$WEBMAIL
      - WEBROOT_REDIRECT=$WEBROOT_REDIRECT
      - WEBSITE=$WEBSITE
      - WELCOME=$WELCOME
      - WELCOME_BODY=$WELCOME_BODY
      - WELCOME_SUBJECT=$WELCOME_SUBJECT
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "$JOHNCLOUD_ROOT/mailu/mailqueue:/queue"
      - "$JOHNCLOUD_ROOT/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - "traefik.enable=false"

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2.0}
    hostname: oletools
    container_name: oletools
    restart: unless-stopped
    environment:
      - ADMIN=$ADMIN
      - ANTIVIRUS=$ANTIVIRUS
      - API=$API
      - API_TOKEN=$API_TOKEN
      - AUTH_RATELIMIT_IP=$AUTH_RATELIMIT_IP
      - AUTH_RATELIMIT_USER=$AUTH_RATELIMIT_USER
      - COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME
      - COMPRESSION=$COMPRESSION
      - COMPRESSION_LEVEL=$COMPRESSION_LEVEL
      - CREDENTIAL_ROUNDS=$CREDENTIAL_ROUNDS
      - DEFAULT_SPAM_THRESHOLD=$DEFAULT_SPAM_THRESHOLD
      - DISABLE_STATISTICS=$DISABLE_STATISTICS
      - DMARC_RUA=$DMARC_RUA
      - DMARC_RUF=$DMARC_RUF
      - DOMAIN=$DOMAIN
      - FETCHMAIL_DELAY=$FETCHMAIL_DELAY
      - FETCHMAIL_ENABLED=$FETCHMAIL_ENABLED
      - HOSTNAMES=$HOSTNAMES
      - INITIAL_ADMIN_ACCOUNT=$INITIAL_ADMIN_ACCOUNT
      - INITIAL_ADMIN_DOMAIN=$INITIAL_ADMIN_DOMAIN
      - INITIAL_ADMIN_MODE=$INITIAL_ADMIN_MODE
      - INITIAL_ADMIN_PW=$INITIAL_ADMIN_PW
      - LOG_LEVEL=$LOG_LEVEL
      - MESSAGE_RATELIMIT=$MESSAGE_RATELIMIT
      - MESSAGE_SIZE_LIMIT=$MESSAGE_SIZE_LIMIT
      - POSTMASTER=$POSTMASTER
      - REAL_IP_FROM=$REAL_IP_FROM
      - REAL_IP_HEADER=$REAL_IP_HEADER
      - RECIPIENT_DELIMITER=$RECIPIENT_DELIMITER
      - REJECT_UNLISTED_RECIPIENT=$REJECT_UNLISTED_RECIPIENT
      - RELAYHOST=$RELAYHOST
      - RELAYNETS=$RELAYNETS
      - SCAN_MACROS=$SCAN_MACROS
      - SECRET_KEY=$SECRET_KEY
      - SITENAME=$SITENAME
      - SUBNET=$SUBNET
      - TLS_FLAVOR=$TLS_FLAVOR
      - TZ=$TZ
      - WEB_ADMIN=$WEB_ADMIN
      - WEB_API=$WEB_API
      - WEB_WEBMAIL=$WEB_WEBMAIL
      - WEBDAV=$WEBDAV
      - WEBMAIL=$WEBMAIL
      - WEBROOT_REDIRECT=$WEBROOT_REDIRECT
      - WEBSITE=$WEBSITE
      - WELCOME=$WELCOME
      - WELCOME_BODY=$WELCOME_BODY
      - WELCOME_SUBJECT=$WELCOME_SUBJECT
    networks:
      - noinet
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - "traefik.enable=false"

  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2.0}
    hostname: antispam
    restart: unless-stopped
    container_name: antispam
    environment:
      - ADMIN=$ADMIN
      - ANTIVIRUS=$ANTIVIRUS
      - API=$API
      - API_TOKEN=$API_TOKEN
      - AUTH_RATELIMIT_IP=$AUTH_RATELIMIT_IP
      - AUTH_RATELIMIT_USER=$AUTH_RATELIMIT_USER
      - COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME
      - COMPRESSION=$COMPRESSION
      - COMPRESSION_LEVEL=$COMPRESSION_LEVEL
      - CREDENTIAL_ROUNDS=$CREDENTIAL_ROUNDS
      - DEFAULT_SPAM_THRESHOLD=$DEFAULT_SPAM_THRESHOLD
      - DISABLE_STATISTICS=$DISABLE_STATISTICS
      - DMARC_RUA=$DMARC_RUA
      - DMARC_RUF=$DMARC_RUF
      - DOMAIN=$DOMAIN
      - FETCHMAIL_DELAY=$FETCHMAIL_DELAY
      - FETCHMAIL_ENABLED=$FETCHMAIL_ENABLED
      - HOSTNAMES=$HOSTNAMES
      - INITIAL_ADMIN_ACCOUNT=$INITIAL_ADMIN_ACCOUNT
      - INITIAL_ADMIN_DOMAIN=$INITIAL_ADMIN_DOMAIN
      - INITIAL_ADMIN_MODE=$INITIAL_ADMIN_MODE
      - INITIAL_ADMIN_PW=$INITIAL_ADMIN_PW
      - LOG_LEVEL=$LOG_LEVEL
      - MESSAGE_RATELIMIT=$MESSAGE_RATELIMIT
      - MESSAGE_SIZE_LIMIT=$MESSAGE_SIZE_LIMIT
      - POSTMASTER=$POSTMASTER
      - REAL_IP_FROM=$REAL_IP_FROM
      - REAL_IP_HEADER=$REAL_IP_HEADER
      - RECIPIENT_DELIMITER=$RECIPIENT_DELIMITER
      - REJECT_UNLISTED_RECIPIENT=$REJECT_UNLISTED_RECIPIENT
      - RELAYHOST=$RELAYHOST
      - RELAYNETS=$RELAYNETS
      - SCAN_MACROS=$SCAN_MACROS
      - SECRET_KEY=$SECRET_KEY
      - SITENAME=$SITENAME
      - SUBNET=$SUBNET
      - TLS_FLAVOR=$TLS_FLAVOR
      - TZ=$TZ
      - WEB_ADMIN=$WEB_ADMIN
      - WEB_API=$WEB_API
      - WEB_WEBMAIL=$WEB_WEBMAIL
      - WEBDAV=$WEBDAV
      - WEBMAIL=$WEBMAIL
      - WEBROOT_REDIRECT=$WEBROOT_REDIRECT
      - WEBSITE=$WEBSITE
      - WELCOME=$WELCOME
      - WELCOME_BODY=$WELCOME_BODY
      - WELCOME_SUBJECT=$WELCOME_SUBJECT
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - noinet
    volumes:
      - "$JOHNCLOUD_ROOT/mailu/filter:/var/lib/rspamd"
      - "$JOHNCLOUD_ROOT/mailu/overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - oletools
      - antivirus
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - "traefik.enable=false"

  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    container_name: antivirus
    environment:
      - ADMIN=$ADMIN
      - ANTIVIRUS=$ANTIVIRUS
      - API=$API
      - API_TOKEN=$API_TOKEN
      - AUTH_RATELIMIT_IP=$AUTH_RATELIMIT_IP
      - AUTH_RATELIMIT_USER=$AUTH_RATELIMIT_USER
      - COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME
      - COMPRESSION=$COMPRESSION
      - COMPRESSION_LEVEL=$COMPRESSION_LEVEL
      - CREDENTIAL_ROUNDS=$CREDENTIAL_ROUNDS
      - DEFAULT_SPAM_THRESHOLD=$DEFAULT_SPAM_THRESHOLD
      - DISABLE_STATISTICS=$DISABLE_STATISTICS
      - DMARC_RUA=$DMARC_RUA
      - DMARC_RUF=$DMARC_RUF
      - DOMAIN=$DOMAIN
      - FETCHMAIL_DELAY=$FETCHMAIL_DELAY
      - FETCHMAIL_ENABLED=$FETCHMAIL_ENABLED
      - HOSTNAMES=$HOSTNAMES
      - INITIAL_ADMIN_ACCOUNT=$INITIAL_ADMIN_ACCOUNT
      - INITIAL_ADMIN_DOMAIN=$INITIAL_ADMIN_DOMAIN
      - INITIAL_ADMIN_MODE=$INITIAL_ADMIN_MODE
      - INITIAL_ADMIN_PW=$INITIAL_ADMIN_PW
      - LOG_LEVEL=$LOG_LEVEL
      - MESSAGE_RATELIMIT=$MESSAGE_RATELIMIT
      - MESSAGE_SIZE_LIMIT=$MESSAGE_SIZE_LIMIT
      - POSTMASTER=$POSTMASTER
      - REAL_IP_FROM=$REAL_IP_FROM
      - REAL_IP_HEADER=$REAL_IP_HEADER
      - RECIPIENT_DELIMITER=$RECIPIENT_DELIMITER
      - REJECT_UNLISTED_RECIPIENT=$REJECT_UNLISTED_RECIPIENT
      - RELAYHOST=$RELAYHOST
      - RELAYNETS=$RELAYNETS
      - SCAN_MACROS=$SCAN_MACROS
      - SECRET_KEY=$SECRET_KEY
      - SITENAME=$SITENAME
      - SUBNET=$SUBNET
      - TLS_FLAVOR=$TLS_FLAVOR
      - TZ=$TZ
      - WEB_ADMIN=$WEB_ADMIN
      - WEB_API=$WEB_API
      - WEB_WEBMAIL=$WEB_WEBMAIL
      - WEBDAV=$WEBDAV
      - WEBMAIL=$WEBMAIL
      - WEBROOT_REDIRECT=$WEBROOT_REDIRECT
      - WEBSITE=$WEBSITE
      - WELCOME=$WELCOME
      - WELCOME_BODY=$WELCOME_BODY
      - WELCOME_SUBJECT=$WELCOME_SUBJECT
    volumes:
      - "$JOHNCLOUD_ROOT/mailu/filter:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - "traefik.enable=false"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
  noinet:
    driver: bridge
    internal: true
