services:
  gatesentry:
    restart: unless-stopped
    image: abdullahi1/gatesentry:latest
    ports:
      # - "80:80"
      - "53:53"
      - "10413:10413"
      # - "10786:10786"
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/config:/usr/local/gatesentry/gatesentry # this is where the config file will be stored
    labels:
      - "traefik.enable=true"

      ### Web UI (HTTP/HTTPS)
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME-ui.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME-ui.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME-ui.tls.certresolver=letsencrypt"
      - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-ui.service=$COMPOSE_PROJECT_NAME-ui"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME-ui.loadbalancer.server.port=10786"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://${HOST}/"
      - "homepage.description=$HOME_DESCRIPTION"

      ### DNS-over-TLS (853 Traefik -> 53 Pi-hole)
      # - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-dot.rule=HostSNI(`$HOST`)""
      # - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-dot.entrypoints=dot"
      # - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-dot.tls.certresolver=letsencrypt"
      # - "traefik.tcp.routers.$COMPOSE_PROJECT_NAME-dot.service=$COMPOSE_PROJECT_NAME-dot"
      # - "traefik.tcp.services.$COMPOSE_PROJECT_NAME-dot.loadbalancer.server.port=53"
      # - "traefik.tcp.services.$COMPOSE_PROJECT_NAME-dot.loadbalancer.proxyProtocol.version=2"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
