services:
  bricktracker:
    image: gitea.baerentsen.space/frederikbaerentsen/bricktracker:latest
    restart: unless-stopped
    environment:
      - REBRICKABLE_API_KEY=$REBRICKABLE_API_KEY
      - DOMAIN_NAME=https://${HOST}
      - LINKS=$LINKS #optional, enables set numbers to be Rebrickable links on the front page
      - RANDOM=$RANDOM #optional, set to True if you want your front page to be shuffled on load
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/static/parts:/app/static/parts
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/static/instructions:/app/static/instructions
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/static/sets:/app/static/sets
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/static/minifigs:/app/static/minifigs
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/app.db:/app/app.db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=3333"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://${HOST}"
      - "homepage.description=$HOME_DESCRIPTION"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
