# https://dev.funkwhale.audio/funkwhale/funkwhale/raw/1.3.4/deploy/docker-compose.yml
version: "3"

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - $JOHNCLOUD_ROOT/funkwhale/postgres:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - $JOHNCLOUD_ROOT/funkwhale/redis:/data
    labels:
      - "traefik.enable=false"

  celeryworker:
    image: funkwhale/api:stable
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    # Celery workers handle background tasks (such file imports or federation
    # messaging). The more processes a worker gets, the more tasks
    # can be processed in parallel. However, more processes also means
    # a bigger memory footprint.
    # By default, a worker will span a number of process equal to your number
    # of CPUs. You can adjust this, by explicitly setting the --concurrency
    # flag:
    #   celery -A funkwhale_api.taskapp worker -l INFO --concurrency=4
    command:
      - celery
      - --app=funkwhale_api.taskapp
      - worker
      - --loglevel=INFO
      - --concurrency=${CELERYD_CONCURRENCY-0}
    environment:
      - C_FORCE_ROOT=true
      - DATABASE_URL=postgresql://postgres:$POSTGRES_PASSWORD@$COMPOSE_PROJECT_NAME-postgres-1/$POSTGRES_DB
      - CACHE_URL=redis://$COMPOSE_PROJECT_NAME-redis-1:6379/0
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - LOGLEVEL=$LOGLEVEL
      - FUNKWHALE_HOSTNAME=$FUNKWHALE_HOSTNAME
      - FUNKWHALE_PROTOCOL=$FUNKWHALE_PROTOCOL
      - FUNKWHALE_WEB_WORKERS=$FUNKWHALE_WEB_WORKERS
      - FUNKWHALE_API_IP=$FUNKWHALE_API_IP
      - FUNKWHALE_API_PORT=$FUNKWHALE_API_PORT
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - EMAIL_CONFIG=$EMAIL_CONFIG
      - ACCOUNT_EMAIL_VERIFICATION_ENFORCE=$ACCOUNT_EMAIL_VERIFICATION_ENFORCE
      - DEFAULT_FROM_EMAIL=$DEFAULT_FROM_EMAIL
      - REVERSE_PROXY_TYPE=apache2
    volumes:
      - $JOHNCLOUD_ROOT/nextcloud/data/data/ydethe/files/Musique:/music:ro"
    labels:
      - "traefik.enable=false"

  celerybeat:
    image: funkwhale/api:stable
    restart: unless-stopped
    command:
      - celery
      - --app=funkwhale_api.taskapp
      - beat
      - --loglevel=INFO
    environment:
      - DATABASE_URL=postgresql://postgres:$POSTGRES_PASSWORD@$COMPOSE_PROJECT_NAME-postgres-1/$POSTGRES_DB
      - CACHE_URL=redis://$COMPOSE_PROJECT_NAME-redis-1:6379/0
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - LOGLEVEL=$LOGLEVEL
      - FUNKWHALE_HOSTNAME=$FUNKWHALE_HOSTNAME
      - FUNKWHALE_PROTOCOL=$FUNKWHALE_PROTOCOL
      - FUNKWHALE_WEB_WORKERS=$FUNKWHALE_WEB_WORKERS
      - FUNKWHALE_API_IP=$FUNKWHALE_API_IP
      - FUNKWHALE_API_PORT=$FUNKWHALE_API_PORT
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - EMAIL_CONFIG=$EMAIL_CONFIG
      - ACCOUNT_EMAIL_VERIFICATION_ENFORCE=$ACCOUNT_EMAIL_VERIFICATION_ENFORCE
      - DEFAULT_FROM_EMAIL=$DEFAULT_FROM_EMAIL
      - REVERSE_PROXY_TYPE=apache2
    depends_on:
      - postgres
      - redis
    labels:
      - "traefik.enable=false"

  api:
    image: funkwhale/api:stable
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - $FUNKWHALE_API_PORT:$FUNKWHALE_API_PORT
    environment:
      - DATABASE_URL=postgresql://postgres:$POSTGRES_PASSWORD@$COMPOSE_PROJECT_NAME-postgres-1/$POSTGRES_DB
      - CACHE_URL=redis://$COMPOSE_PROJECT_NAME-redis-1:6379/0
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - LOGLEVEL=$LOGLEVEL
      - FUNKWHALE_HOSTNAME=$FUNKWHALE_HOSTNAME
      - FUNKWHALE_PROTOCOL=$FUNKWHALE_PROTOCOL
      - FUNKWHALE_WEB_WORKERS=$FUNKWHALE_WEB_WORKERS
      - FUNKWHALE_API_IP=$FUNKWHALE_API_IP
      - FUNKWHALE_API_PORT=$FUNKWHALE_API_PORT
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - EMAIL_CONFIG=$EMAIL_CONFIG
      - ACCOUNT_EMAIL_VERIFICATION_ENFORCE=$ACCOUNT_EMAIL_VERIFICATION_ENFORCE
      - DEFAULT_FROM_EMAIL=$DEFAULT_FROM_EMAIL
      - REVERSE_PROXY_TYPE=apache2
    volumes:
      - $JOHNCLOUD_ROOT/nextcloud/data/data/ydethe/files/Musique:/music:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.funkwhale-api.rule=Host(`api.$HOST`)"
      - "traefik.http.routers.funkwhale-api.entrypoints=websecure"
      - "traefik.http.routers.funkwhale-api.tls.certResolver=letsencrypt"

  front:
    restart: unless-stopped
    image: funkwhale/front:stable
    depends_on:
      - api
    environment:
      - DATABASE_URL=postgresql://postgres:$POSTGRES_PASSWORD@$COMPOSE_PROJECT_NAME-postgres-1/$POSTGRES_DB
      - CACHE_URL=redis://$COMPOSE_PROJECT_NAME-redis-1:6379/0
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - LOGLEVEL=$LOGLEVEL
      - FUNKWHALE_HOSTNAME=$FUNKWHALE_HOSTNAME
      - FUNKWHALE_PROTOCOL=$FUNKWHALE_PROTOCOL
      - FUNKWHALE_WEB_WORKERS=$FUNKWHALE_WEB_WORKERS
      - FUNKWHALE_API_IP=$FUNKWHALE_API_IP
      - FUNKWHALE_API_PORT=$FUNKWHALE_API_PORT
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - EMAIL_CONFIG=$EMAIL_CONFIG
      - ACCOUNT_EMAIL_VERIFICATION_ENFORCE=$ACCOUNT_EMAIL_VERIFICATION_ENFORCE
      - DEFAULT_FROM_EMAIL=$DEFAULT_FROM_EMAIL
      - REVERSE_PROXY_TYPE=apache2
      - NGINX_MAX_BODY_SIZE=100M
      - MEDIA_ROOT=/srv/funkwhale/data/media
      - STATIC_ROOT=/srv/funkwhale/data/static
      - MUSIC_DIRECTORY_PATH=/music
      - MUSIC_DIRECTORY_SERVE_PATH=/srv/funkwhale/data/music
    volumes:
      - $JOHNCLOUD_ROOT/nextcloud/data/data/ydethe/files/Musique:/music:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.funkwhale-web.rule=Host(`$HOST`)"
      - "traefik.http.routers.funkwhale-web.entrypoints=websecure"
      - "traefik.http.routers.funkwhale-web.tls.certResolver=letsencrypt"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
    

